Fix #76, #82, #83, update docs, more constistent `opt <pattern> or <default>` implementation (#77)
* [TEST]

* [TEST] More tests

* [FIX] #76

* [TEST] String length test

* [DOC] Spec for `opt`

* [DOC] `doc` interaction with `any`

* [DOC] Scale back `opt` features

* [CHECKPOINT] Initial `opt` implementation

* [FEATURE] `opt` implementation

- ADDED ::
  - implement `opt` for field access

* [FIX] Additional check for `nil` values

- CHANGED ::
  Before calling check function on nested match element check using
  `isNil` if entry can is correct. This avoids almost unfixable
  nil-based exceptions triggered deeply within pattern.

* [CLEAN] Internal naming cleanup

- CHANGED ::
  - Use more readable, unabreviated field names (cnt -> foundCount,
    fldElems -> fieldElements)

* [FIX] make style check shut the fuck up

* [FIX] Also bitch with error on typos

* [FIX] oh no, stdlib does not pass style check

 Compiling /home/runner/work/fusion/fusion/fusion/tests/tmatching (from package fusion) using c backend
Error: /home/runner/work/fusion/fusion/nim/lib/std/private/underscored_calls.nim(43, 21) Error: 'nnkArgList' should be: 'nnkArglist'
       Tip: 5 messages have been suppressed, use --verbose to show them.

* [DOC]

* [FIX] Support qualified variant selectors with matching? #83

* [CLEAN] debug prints

* [TEST] Decision matrix predicate test

* [DOC] Predicates and infix operators

* [FIX] Use peg instead of regex for example test

* [FIX] Duplicate assign for matches with conditions

* [CHECKPOINT]